runtime: go121

env_variables:
  NETRECEIVER_CREDENTIALS: gs://ausocean/NetReceiver-55f1f53a6d8a.json
  VIDGRIND_CREDENTIALS: gs://ausocean/VideoGrinder-b0ad82abac05.json
  YOUTUBE_SECRETS: gs://ausocean/YouTube-secrets.json
  OCEANTV_SECRETS: gs://ausocean/OceanTV-secrets.txt
  OPS_EMAIL: ops@ausocean.org
  OPS_PERIOD: 60

handlers:
  - url: /.*
    secure: always
    script: auto
