runtime: go121

env_variables:
  NETRECEIVER_CREDENTIALS: gs://ausocean/NetReceiver-55f1f53a6d8a.json
  VIDGRIND_CREDENTIALS: gs://ausocean/VideoGrinder-b0ad82abac05.json
  OCEANBENCH_SECRETS: gs://ausocean/OceanBench-secrets.txt
  OCEANCRON_SECRETS: gs://ausocean/OceanCron-secrets.txt
  YOUTUBE_SECRETS: gs://ausocean/YouTube-secrets.json
  OAUTH2_CALLBACK: https://bench.cloudblue.org/oauth2callback
  OPS_EMAIL: ops@ausocean.org
  OPS_PERIOD: 60
  VIDGRIND_EXPERIMENTS: TRIM_MTS

handlers:
  - url: /favicon\.ico
    static_files: favicon.ico
    upload: favicon\.ico

  - url: /s
    static_dir: s

  - url: /(poll|act|recv|vars|config|api|test).*
    script: auto

  - url: /.*
    secure: always
    script: auto
